# Generated by Django 3.1.4 on 2022-03-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='tulov',
            field=models.BooleanField(default=False),
        ),
    ]
